name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: stable
          cache: true

      - name: Check Flutter
        run: flutter --version

      - name: Generate Android project
        run: flutter create --platforms=android .

      - name: Set Android minSdk
        run: |
          FILE=$(find android/app -maxdepth 1 -type f \( -name "build.gradle" -o -name "build.gradle.kts" \) | head -n 1)

          echo "Using: $FILE"

          if [[ "$FILE" == *.kts ]]; then
            sed -i 's/minSdk = flutter.minSdkVersion/minSdk = 23/g' "$FILE"
          else
            sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 23/g' "$FILE"
          fi

          cat "$FILE"

      - name: Clean old build files
        run: |
          flutter clean
          rm -rf build
          rm -rf .dart_tool

      - name: Get dependencies
        run: flutter pub get

      - name: Show dependencies
        run: flutter pub deps

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
